# Generated by Django 3.0.3 on 2020-05-22 20:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('comms', '0002_auto_20200522_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid event title', message='Event title must be alphanumeric', regex='^[a-zA-Z0-9 ]*$')])),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('recurring', models.BooleanField(default=False)),
                ('description', models.TextField(default='', max_length=150, validators=[django.core.validators.RegexValidator(code='invalid event description', message='Only use alphanumerics please', regex='^[a-zA-Z0-9 .,]*$')])),
                ('website_publish', models.BooleanField(default=False)),
                ('recurrence_interval', models.PositiveSmallIntegerField(choices=[(1, 'Set event to daily recurrence'), (2, 'Set event to weekly recurrence'), (3, 'Set event to monthly recurrence'), (4, 'Set event to yearly recurrence')], default=2)),
                ('slug', models.SlugField(default=None, editable=False, max_length=80, unique=True)),
                ('event_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_owners_set', to='people.Person')),
                ('invites', models.ManyToManyField(to='comms.CommsGroup')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
