# Generated by Django 3.0.3 on 2020-05-22 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=150, validators=[django.core.validators.RegexValidator(code='invalid event description', message='Only use alphanumerics please', regex='^[a-zA-Z0-9 .,\r\n]*$')]),
        ),
    ]
