# Generated by Django 3.0.3 on 2020-05-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200522_2123'),
        ('events', '0002_auto_20200522_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_owners_set', to='people.Person'),
        ),
    ]
