# Generated by Django 3.0.7 on 2020-07-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200523_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurring',
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence_interval',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Set event to non-recurring'), (1, 'Set event to daily recurrence'), (2, 'Set event to weekly recurrence'), (3, 'Set event to monthly recurrence'), (4, 'Set event to yearly recurrence')], default=2),
        ),
    ]
