# Generated by Django 3.0.7 on 2020-07-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200730_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=None, editable=False, max_length=80, null=True, unique=True),
        ),
    ]
