# Generated by Django 3.0.7 on 2020-07-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200731_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=None, max_length=80, unique=True),
        ),
    ]
