# Generated by Django 3.0.3 on 2020-05-22 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_info_link', models.URLField(max_length=250)),
                ('ticket_link', models.URLField(max_length=250)),
                ('contact_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter number in valid format only', regex='^\\+?1?\\d{9,15}$')])),
                ('twitter_link', models.URLField(max_length=250)),
                ('facebook_link', models.URLField(max_length=250)),
                ('linked_organisation', models.URLField(max_length=250)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'ordering': ['event'],
            },
        ),
    ]
