# Generated by Django 3.0.7 on 2020-09-12 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('2f74286b-7c3f-40d8-97d1-b4f4bfd257d5')),
        ),
    ]
