# Generated by Django 3.0.7 on 2020-09-06 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommsGroup',
            fields=[
                ('group_name', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid event in group_name', message='Please use alphanumeric only', regex='^[A-Z0-9a-z ]*$')])),
                ('group_purpose', models.TextField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid event in group_purpose', message='Please use alphanumeric only', regex='^[A-Z0-9a-z, \r\n]*$')])),
                ('slug', models.SlugField(default=None, editable=False, unique=True)),
                ('group_membership', models.ManyToManyField(blank=True, to='people.Person')),
                ('group_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owners_set', to='people.Person')),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
    ]
