# Generated by Django 3.0.3 on 2020-05-22 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommsGroup',
            fields=[
                ('group_name', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid event in group_name', message='Please use alphanumeric only', regex='^[A-Z0-9a-z ]*$')])),
                ('group_purpose', models.TextField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid event in group_purpose', message='Please use alphanumeric only', regex='^[A-Z0-9a-z, ]*$')])),
                ('slug', models.SlugField(default=None, editable=False, unique=True)),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
    ]
