# Generated by Django 3.0.3 on 2020-05-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commsgroup',
            name='group_membership',
            field=models.ManyToManyField(blank=True, to='people.Person'),
        ),
        migrations.AddField(
            model_name='commsgroup',
            name='group_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owners_set', to='people.Person'),
        ),
    ]
