# Generated by Django 3.0.3 on 2020-05-22 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_auto_20200522_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commsgroup',
            name='group_purpose',
            field=models.TextField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid event in group_purpose', message='Please use alphanumeric only', regex='^[A-Z0-9a-z, \r\n]*$')]),
        ),
    ]
