# Generated by Django 3.0.3 on 2020-05-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200522_2123'),
        ('comms', '0004_auto_20200523_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commsgroup',
            name='group_membership',
            field=models.ManyToManyField(blank=True, to='people.Person'),
        ),
    ]
