# Generated by Django 3.0.3 on 2020-05-22 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid event in address', message='Please use alphanumeric only', regex='^[A-Z0-9a-z, \r\n]*$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(max_length=500, validators=[django.core.validators.RegexValidator(code='invalid event in notes', message='Please use alphanumeric only', regex='^[A-Z0-9a-z, .\r\n]*$')]),
        ),
    ]
