# Generated by Django 3.0.3 on 2020-05-25 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_role_associated_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='working_hrs',
            name='id',
        ),
        migrations.AddField(
            model_name='working_hrs',
            name='shift_name',
            field=models.CharField(default='first shift', max_length=80, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid shift name', message='Shift name must be alphanumeric', regex='^[a-zA-Z0-9 ]*$')]),
        ),
        migrations.AddField(
            model_name='working_hrs',
            name='slug',
            field=models.SlugField(default=None, editable=False, max_length=80, unique=True),
        ),
    ]
